### ISSUE TITLE
Determine communication packet format between all subsystems

### ISSUE THREAD

**Issue by dbcarelli** [dbcarelli/qgroundcontrol-mission-mule#1]
We need to agree on how information will be sent from in each of the three cases:
1. Uploading a new mission (presumably, this is simple--through our custom mavlink command)
2. Configuring a new data station (data will come in over the USB serial port, using the XBee)
3. Deploying a data station (again, data will come in over the USB serial port using XBee)

**Comment by dbcarelli** [comment]
Ok, lets agree on this now:
**Item 1**
In order for the drone companion computer to identify a Data Station type waypoint, it will look at parameter number 1 of all MAV_CMD_NAV_WAYPOINT (CMD 16) read in from the Pixhawk Autopilot. If this number is greater than 1, then it will assume a data station. Otherwise it will assume a normal navigation waypoint. 
**Item 2**
In order to configure a new data station, the following bytes must be sent over XBee from QGC:
1. The preamble, the following string of ASCII characters: ['s', 't', 'r', 'e', 'e', 't']
2. The command ID: a numeric 4 will correspond to "Data Station ID Reset" command
3. At this point the data station will expect a pre-limitor: ASCII '<'
4. The next two bytes will be the Data station ID, which will be ASCII characters representing numbers from 0 to 9
5. The next byte will be a post-limitor: ASCII '>'
6. Finally, if the camera successfully changes its ID it will return the response pre-amble: ['c','a','t']

**Item 3**
In order to receive the relevant information from a newly deployed camera trap, the following bytes must be sent over XBee from QGC:
1. The preamble, the following string of ASCII characters: ['s', 't', 'r', 'e', 'e', 't']
2. The target data station ID
3. The command ID: a numeric 5 will correspond to "Data Station Status Request" command
4  The data station will return the response pre-amble: ['c','a','t']
5. Next, the data station will send a single pre-limitor: ASCII character for '<'
6. The data station will its GPS coordinates in as many bytes necessary
7. The next byte will be a post-limitor: ASCII '>'

@Moni286 @Annerion please confirm that you've seen this and agree.

**Comment by Annerion** [comment]
I have seen this a mostly agree, except that from y memory hold time was parameter 2 in MAV_CMD_NAV_WAYPOINT. Otherwise good.

**Comment by mounir-khaled** [comment]
No. It is actually param 1. I just checked.

**Comment by dbcarelli** [comment]
![image](https://user-images.githubusercontent.com/14120384/38202496-f57b4432-36ac-11e8-97bd-f401c64dfb3c.png)
