### ISSUE TITLE
DataStationManager API changes

### ISSUE THREAD

**Issue by mounir-khaled** [dbcarelli/qgroundcontrol-mission-mule#15]
- Track selected DataStation in spreadsheet
- emit dataStationsChanged signal
- Make all DataStation attributes Q_PROPERTY

**Comment by mounir-khaled** [comment]
dataStationsChanged emitted

**Comment by mounir-khaled** [comment]
DataStation attributes are Q_PROPERTIES with read access only

**Comment by Annerion** [comment]
This round of API changes were successful and enabled most of the functionality needed.
