### ISSUE TITLE
StaticMetaObject has no attribute DataStation

### ISSUE THREAD

**Issue by Annerion** [dbcarelli/qgroundcontrol-mission-mule#16]
Lots of build errors with the current development, mostly stemming from  the error StaticMetaObject has no attribute DataStation. 

@Moni286 I fixed the issue by uncomenting the part of the line that says DataStation is a child of QObject, but I want to be sure that is what you intended before I fix those changes.

**Comment by mounir-khaled** [comment]
Ok sounds good. Try also commenting the line in the DataStationManager that
registers DataStation as a type and see if it works.

**Comment by Annerion** [comment]
Fixed
