### ISSUE TITLE
Make getters and setters for DataStationManager

### ISSUE THREAD

**Issue by dbcarelli** [dbcarelli/qgroundcontrol-mission-mule#17]
It's turning out to be a real pain in the ass to work with the DataStationManager and DataStations within QML files. I propose making getters and setters in DataStationManager to make it straigh forward to interface from QMLs. If you think about it, the DataStationManager is simply an interface, so it makes sense that it send more primitive types to highler level files. 

This would also make our additions more human-readable which allows for quicker de-bug and on-boarding for future members. As an example, the QML portion should read like this:

`for (var i = 0; i < dataStationManager.numOfActiveStations(); i++){`
`    insertDataSation(dataSationManager.lat(i), dataStationManger.lon(i));`     
`}`

@Moni286 , @Annerion Thoughts? I can do this on a branch and merge into dev if you guys are ok with this

**Comment by mounir-khaled** [comment]
I think the way DataStationManager is being accessed in the QML files is
the problem. If you like, you can work on this in another branch while I
try to make the QML work with what we have.

But basically, what I’ve seen in other files is similar to what we’ve done
up until now.

**Comment by dbcarelli** [comment]
Aright, at the very least can make a coordinate getter that returns a QGeoCoordinate?
I made one for my sake, but would probs be nice to have for good:

`Q_INVOKABLE QGeoCoordinate coordinate(int index) {`
       `QGeoCoordinate retVal = QGeoCoordinate();`
       `retVal.setLongitude(24.521760);`
      ` retVal.setLatitude(54.432304);`
     `  return retVal;`
    `}`

**Comment by Annerion** [comment]
Done
