### ISSUE TITLE
Register QList<DataStation> with qml

### ISSUE THREAD

**Issue by Annerion** [dbcarelli/qgroundcontrol-mission-mule#18]
QMetaProperty::read: Unable to handle unregistered datatype 'QList<DataStation*>' for property 'DataStationManager::dataStations'

Is the error I am getting when attempting to work on the Qml page. I will register it in my code for the time being, but it would be better if @Moni286 to make this change for API consistency.

**Comment by Annerion** [comment]
From my early attempts, it may be necessary to make a custom list, as Qlist doesn't seem to be a QObject

**Comment by mounir-khaled** [comment]
I am looking at your branch now. I'll see if I can fix it. If not, we could discuss other ways to go about this.

**Comment by Annerion** [comment]
We found a different approach, which has been implemented.
