### ISSUE TITLE
Integrate XBee Serial Communication

### ISSUE THREAD

**Issue by mounir-khaled** [dbcarelli/qgroundcontrol-mission-mule#4]
Instead of creating our own SerialLink files, we can use the ones already implemented in QGroundControl. It takes care of all the cross-platform issues, and we can guarantee its functionality. It would also provide better integration with the QGroundControl project rather than creating our own SerialLink class.

We would still need to implement the protocol that we want to use, and what it does with that communication; request position, save to file, etc...

**Comment by dbcarelli** [comment]
Mounir, you'll bee integrating the DataStationLink class into the overall QGC framework with the dummy functions we made. In the meantime, I'll start writing the communication protocol so that it sends what the Data STations are expecting #7

**Comment by mounir-khaled** [comment]
The DataStationLink class will act as our protocol parser, since the protocol seems to be pretty straightforward. I am writing a singleton class "DataStationManager," that can be called from the GUI. This class will contain a list of known data stations, as well as the methods necessary to communicate with a connected data station.

**Comment by dbcarelli** [comment]
@Moni286 is this done?

**Comment by mounir-khaled** [comment]
With the new updates, we now have the protocol implemented in the
DataStationLink class. The DataStationManager is integrated within the QGC
framework and it works in parallel with their LinkManager. We can close
this issue.
