### ISSUE TITLE
Adding Spreadsheet View

### ISSUE THREAD

**Issue by Annerion** [dbcarelli/qgroundcontrol-mission-mule#5]
The spreadsheet should:

1. Automatically add connected Data Stations to the speadsheet
2. Reflect changes made through map view and vice versa
3. Be directly accessible as a view inside qgc

**Comment by dbcarelli** [comment]
@Annerion, any progress on this? Have you looked into how you might implement it? I will try and help with this today.

**Comment by dbcarelli** [comment]
@Annerion, A possible way to accomplish this is to mimic the log download pane in the Analyze view. I was quickly messing around with this and managed to add another button by modifying the AnalyzeView.qml file:

![image](https://user-images.githubusercontent.com/14120384/38806856-b4fa7574-418b-11e8-8ccd-6f7423e79179.png)

When this new button is pressend it simply pulls up the MavlinkConsolePage.qml, but my guess is that we can simply call up a modified version of LogDownloadPage.qml. What do you think?

**Comment by dbcarelli** [comment]
@Annerion, close this if it's done.

**Comment by Annerion** [comment]
This is written, but only tested on empty lists of data stations.

**Comment by Annerion** [comment]
Still a few bugs, but works, will put bugs in a new issue.
