### ISSUE TITLE
Pass Complex Mission Items

### ISSUE THREAD

**Issue by Annerion** [dbcarelli/qgroundcontrol-mission-mule#6]
Data Station mission items should be changed to be complex mission items containing 31010 CMD and a 16 CMD. These mission items should be distinct new mission items which contain a standard waypoint and additional information.

**Comment by dbcarelli** [comment]
I'm taking responsibility for this. I was able to accomplish functionality by simply modifying the function that is called when the Data Station button is pressed (PlanView.qml). Here, the function creates a normal SimpleMissionItem with a NAV commands as well as SimpleMissionItem whose Command is overwritten to MAV_CMD_USER_1 (#31010). This builds and works, but the UI needs work.

**Comment by dbcarelli** [comment]
Will reserve param1 for the data station's ID.

**Comment by dbcarelli** [comment]
@Moni286, how are you changing the color of the waypoints (in the old data shation map format). somehow, when marking param1>0, it turns red--where is the code for that?

**Comment by mounir-khaled** [comment]
I don’t remember the name of the qml file, but it’s where the waypoint
display is defined.

**Comment by dbcarelli** [comment]
In dropping a data station, we actually call to drop a SimpleMissionItem (ie a waypoint) with an ROI right after on the same spot. I tried using the user defined command (#31010), but these mission items fail to upload to the pixhawk because it is not recognized. Using ROIs works, so I'm closing this.
